In [1]:
import numpy as np

In [3]:
np.ones((3, 4, 5), dtype=np.float64).strides

(160, 40, 8)

In [6]:
arr = np.arange(12)

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
arr.reshape((4,3), order='C')

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [9]:
arr.reshape((4,3), order='F')

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [11]:
arr.reshape((3, 4), order='F')

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [12]:
arr = np.arange(15)

In [14]:
arr.reshape((6, -1))

ValueError: cannot reshape array of size 15 into shape (6,newaxis)