In [1]:
import numpy as np

In [3]:
np.ones((3, 4, 5), dtype=np.float64).strides

(160, 40, 8)

In [6]:
arr = np.arange(12)

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
arr.reshape((4,3), order='C')

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [9]:
arr.reshape((4,3), order='F')

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [11]:
arr.reshape((3, 4), order='F')

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [2]:
arr = np.arange(15)

In [14]:
arr.reshape((6, -1))

ValueError: cannot reshape array of size 15 into shape (6,newaxis)

In [14]:
arr = np.arange(15).reshape((5, 3))

In [22]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [24]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
arr  = np.arange(10) * 2

In [32]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
inds = [7, 1, 2, 6]

In [34]:
arr[inds]

array([14,  2,  4, 12])

In [35]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
arr.take(inds)

array([14,  2,  4, 12])

In [37]:
# array.take(list) takes the list out of array and returns an array of the list
# array.put(list, int or list) puts the int or list into the array in the places of list

In [38]:
arr = np.random.randn(4, 3)

In [39]:
arr

array([[ 1.94613259, -0.56941304,  0.2379554 ],
       [-0.26424771,  0.60382425,  0.38697699],
       [-0.11445407,  0.25426439, -1.36146182],
       [-0.31445032, -0.70658822, -0.93326188]])

In [40]:
arr.mean(0)

array([ 0.31324512, -0.10447816, -0.41744783])

In [41]:
arr.mean(1)

array([ 0.53822498,  0.24218451, -0.40721717, -0.65143347])

In [43]:
1.94613259 + -0.26424771 + -0.11445407 + -0.31445032

1.25298049

In [45]:
1.25298049 / 4

0.3132451225

In [46]:
(1.94613259 + -0.56941304 + 0.2379554) / 3

0.5382249833333332

In [47]:
demeaned = arr - arr.mean(0)

In [48]:
demeaned

array([[ 1.63288747, -0.46493489,  0.65540323],
       [-0.57749283,  0.7083024 ,  0.80442482],
       [-0.4276992 ,  0.35874255, -0.94401399],
       [-0.62769544, -0.60211006, -0.51581405]])

In [49]:
demeaned.mean(0)

array([-2.77555756e-17,  2.77555756e-17, -2.77555756e-17])

In [50]:
arr = np.zeros((4,4))

In [51]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
arr_3d = arr[:, np.newaxis, :]

In [53]:
arr_3d

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [54]:
arr_3d.shape

(4, 1, 4)

In [55]:
arr_1d = np.random.normal(size = 3)

In [56]:
arr_1d

array([-0.67535461,  0.45003547,  0.87394002])

In [57]:
arr_1d[:, np.newaxis]

array([[-0.67535461],
       [ 0.45003547],
       [ 0.87394002]])

In [58]:
arr_1d[np.newaxis, :]

array([[-0.67535461,  0.45003547,  0.87394002]])

In [59]:
help(np.newaxis)

Help on NoneType object:

class NoneType(object)
 |  Methods defined here:
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.
 |  
 |  __repr__(self, /)
 |      Return repr(self).



In [60]:
arr = np.zeros((4,3))

In [68]:
arr[:] = 5

In [69]:
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [72]:
col = np.array([1.28, -0.42, 0.44, 1.6])

In [73]:
arr[:] = col[:, np.newaxis]

In [74]:
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [76]:
np.info(np.logical_and)

logical_and(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Compute the truth value of x1 AND x2 element-wise.

Parameters
----------
x1, x2 : array_like
    Input arrays. `x1` and `x2` must be of the same shape.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
y : ndarray or bool
    Boolean result with the same shape as `x1` and `x2` of the logical
    AND

In [78]:
x, y = np.random.randn(3, 4), np.random.randn(5)

In [79]:
x

array([[ 0.77256093,  0.43923333,  1.21685679,  0.05738323],
       [-0.52415455,  2.9382465 ,  0.86408808,  0.36068351],
       [ 0.90036746, -1.42013607,  0.05726306,  0.20105308]])

In [80]:
y

array([-0.33699259, -1.94527949,  0.2804763 , -1.45535586,  0.31372051])

In [81]:
result = np.subtract.outer(x, y)

In [82]:
result

array([[[ 1.10955352,  2.71784042,  0.49208463,  2.22791679,
          0.45884041],
        [ 0.77622592,  2.38451282,  0.15875703,  1.89458919,
          0.12551282],
        [ 1.55384938,  3.16213628,  0.93638049,  2.67221265,
          0.90313628],
        [ 0.39437582,  2.00266272, -0.22309307,  1.51273908,
         -0.25633729]],

       [[-0.18716196,  1.42112494, -0.80463085,  0.93120131,
         -0.83787506],
        [ 3.27523908,  4.88352599,  2.6577702 ,  4.39360235,
          2.62452598],
        [ 1.20108067,  2.80936758,  0.58361179,  2.31944394,
          0.55036757],
        [ 0.6976761 ,  2.30596301,  0.08020722,  1.81603937,
          0.046963  ]],

       [[ 1.23736005,  2.84564696,  0.61989117,  2.35572332,
          0.58664695],
        [-1.08314348,  0.52514343, -1.70061236,  0.03521979,
         -1.73385658],
        [ 0.39425564,  2.00254255, -0.22321324,  1.51261891,
         -0.25645746],
        [ 0.53804567,  2.14633258, -0.07942321,  1.65640894,
         -0

In [84]:
result.shape

(3, 4, 5)

In [85]:
0+1+2+3+4

10

In [86]:
4+5+6

15

In [87]:
5+6+7

18

In [88]:
8+9

17

In [89]:
def add_elements(x, y):
    return x + y

In [103]:
add_them = np.frompyfunc(add_elements, 2, 1)

In [104]:
add_them(4, 5)

9

In [106]:
dtype = [('x', np.float64), ('y', np.int32)]

In [108]:
sarr = np.array([(1.5, 6), (np.pi, -2)], dtype=dtype)

In [109]:
sarr

array([(1.5       ,  6), (3.14159265, -2)],
      dtype=[('x', '<f8'), ('y', '<i4')])

In [110]:
sarr[1]['y']

-2

In [111]:
sarr['x']

array([1.5       , 3.14159265])

In [112]:
arr = np.random.randn(6)
arr

array([ 1.31323299, -0.26556974, -2.41969505, -0.07283844, -0.30611304,
       -0.63488777])

In [113]:
arr.sort()
arr

array([-2.41969505, -0.63488777, -0.30611304, -0.26556974, -0.07283844,
        1.31323299])

In [114]:
arr

array([-2.41969505, -0.63488777, -0.30611304, -0.26556974, -0.07283844,
        1.31323299])

In [115]:
arr = np.random.randn(6)
arr

array([-1.85335375, -0.49040951, -0.25506082, -0.24865754, -0.19051214,
       -1.13239434])

In [116]:
np.sort(arr)

array([-1.85335375, -1.13239434, -0.49040951, -0.25506082, -0.24865754,
       -0.19051214])

In [117]:
arr

array([-1.85335375, -0.49040951, -0.25506082, -0.24865754, -0.19051214,
       -1.13239434])

array.sort() actually changes the array
np.sort(array) creates a copy of the array

In [119]:
arr = np.random.randn(3, 5)
arr

array([[-0.00718673, -1.18535943, -0.28705857, -0.60750625, -1.22885974],
       [ 0.55771235, -1.07910228,  1.23660888, -0.54534966, -1.49664713],
       [ 0.16564024,  0.71690709, -1.68078413,  0.32404544, -1.22276798]])

In [120]:
np.sort(arr, axis=1)

array([[-1.22885974, -1.18535943, -0.60750625, -0.28705857, -0.00718673],
       [-1.49664713, -1.07910228, -0.54534966,  0.55771235,  1.23660888],
       [-1.68078413, -1.22276798,  0.16564024,  0.32404544,  0.71690709]])

In [121]:
np.sort(arr, axis=0)

array([[-0.00718673, -1.18535943, -1.68078413, -0.60750625, -1.49664713],
       [ 0.16564024, -1.07910228, -0.28705857, -0.54534966, -1.22885974],
       [ 0.55771235,  0.71690709,  1.23660888,  0.32404544, -1.22276798]])

axis 1 is the row <br/>
axis 0 is the column

In [124]:
arr[:, ::-1]

array([[-1.22885974, -0.60750625, -0.28705857, -1.18535943, -0.00718673],
       [-1.49664713, -0.54534966,  1.23660888, -1.07910228,  0.55771235],
       [-1.22276798,  0.32404544, -1.68078413,  0.71690709,  0.16564024]])

In [123]:
arr

array([[-0.00718673, -1.18535943, -0.28705857, -0.60750625, -1.22885974],
       [ 0.55771235, -1.07910228,  1.23660888, -0.54534966, -1.49664713],
       [ 0.16564024,  0.71690709, -1.68078413,  0.32404544, -1.22276798]])

In [125]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])
sorter = np.lexsort((first_name, last_name))
sorter

array([1, 2, 3, 0, 4], dtype=int64)

In [129]:
zip(last_name[sorter], first_name[sorter])

In [131]:
last_name[sorter]

array(['Arnold', 'Arnold', 'Jones', 'Jones', 'Walters'], dtype='<U7')

In [132]:
first_name[sorter]

array(['Jane', 'Steve', 'Bill', 'Bob', 'Barbara'], dtype='<U7')

In [134]:
last_first = np.array((last_name[sorter], first_name[sorter]))

In [135]:
last_first

array([['Arnold', 'Arnold', 'Jones', 'Jones', 'Walters'],
       ['Jane', 'Steve', 'Bill', 'Bob', 'Barbara']], dtype='<U7')

array([['Arnold', 'Arnold', 'Jones', 'Jones', 'Walters']], dtype='<U7')