In [1]:
import numpy as np

In [6]:
my_arr = np.arange(1000000)

In [7]:
my_list = list(range(1000000))

In [9]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 24 ms


In [12]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 1.14 s


In [15]:
list_test = [1, 2, 3, 4, 5]

In [18]:
min(list_test)

1

In [20]:
np.min(list_test)

1

In [25]:
np.empty((2, 3, 5))

array([[[6.42338869e-312, 9.58487353e-322, 0.00000000e+000,
         0.00000000e+000, 1.29062093e-306],
        [4.82337433e+228, 6.14415221e-144, 1.16097020e-028,
         1.48340347e-076, 1.48397126e-071],
        [5.64694224e-038, 3.97062373e+246, 1.16318408e-028,
         3.43833627e+179, 2.74854789e+180]],

       [[1.00606988e-046, 9.34748247e-067, 5.04621361e+180,
         8.37170571e-144, 3.80985069e+180],
        [3.59751658e+252, 8.93185432e+271, 4.76484771e+180,
         1.01849500e+248, 8.00801703e+159],
        [5.88753758e-091, 7.97225733e-042, 1.03176205e+166,
         1.83160568e-076, 1.30438762e-076]]])

In [26]:
np.empty((4, 3, 5))

array([[[6.42338416e-312, 6.42313292e-312, 0.00000000e+000,
         0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         4.70093814e-308, 6.42337581e-312],
        [6.42331334e-312, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000, 0.00000000e+000

In [27]:
np.zeros((4, 3, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [28]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
np.full((2,2),4)

array([[4, 4],
       [4, 4]])

In [40]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [41]:
arr_round = np.zeros_like(arr)

In [42]:
arr_round = np.round(arr, 0)

In [43]:
arr_round

array([ 4., -1., -3.,  0., 13., 10.])

In [44]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [45]:
arr[0]

3.7

In [53]:
arr_2 = np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9]))

In [49]:
arr_2 = np.zeros((3, 2))

In [54]:
arr_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr_2[0]

array([1, 2, 3])

In [56]:
arr_2[0][1]

2

In [57]:
arr_2[0][1] = 100

In [58]:
arr_2

array([[  1, 100,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [59]:
arr_3 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [60]:
arr_3 = np.array(arr_3)

In [61]:
arr_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# page 95